#!/bin/bash

d=$(dirname "$0")
failed=false

for test in "$d"/*.pl; do
    echo -n "$(basename "${test%.pl}"): "
    if ! diff -s "${test%.pl}.out" <("$d/../../poorlog" -dsanity "$test"); then
        failed=true
        echo "./poorlog" -dsanity "$test"
    fi
done
